version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: go_web
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["go", "run", "migrate/migrate.go"]  # run migrations

  db:
    image: postgres:12
    restart: always
    container_name: go_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: go_crud
